"""Tests for map-agent providers."""

from .test_base import test_poi_creation
from .test_hms import (
    test_hms_provider_creation,
    test_hms_provider_creation_with_timeout,
    test_hms_provider_close,
    test_hms_provider_context_manager,
    test_convert_hms_site_to_poi,
    test_convert_hms_site_to_poi_minimal,
    test_convert_hms_route_to_route,
    test_convert_hms_error_to_api_error,
    test_convert_hms_network_error,
    test_search_nearby_success,
    test_search_nearby_with_category,
    test_search_nearby_error,
    test_keyword_search_success,
    test_poi_detail_success,
    test_poi_detail_not_found,
    test_geocode_success,
    test_reverse_geocode_success,
    test_route_driving_success,
    test_route_walking_success,
    test_route_cycling_success,
    test_route_with_waypoints,
    test_search_suggestion_success,
)

__all__ = [
    "test_poi_creation",
    "test_poi_minimal",
    "test_route_step_creation",
    "test_route_creation",
    "test_geocode_result_creation",
    "test_map_provider_is_abstract",
    "test_hms_provider_creation",
    "test_hms_provider_creation_with_timeout",
    "test_hms_provider_close",
    "test_hms_provider_context_manager",
    "test_convert_hms_site_to_poi",
    "test_convert_hms_site_to_poi_minimal",
    "test_convert_hms_route_to_route",
    "test_convert_hms_error_to_api_error",
    "test_convert_hms_network_error",
    "test_search_nearby_success",
    "test_search_nearby_with_category",
    "test_search_nearby_error",
    "test_keyword_search_success",
    "test_poi_detail_success",
    "test_poi_detail_not_found",
    "test_geocode_success",
    "test_reverse_geocode_success",
    "test_route_driving_success",
    "test_route_walking_success",
    "test_route_cycling_success",
    "test_route_with_waypoints",
    "test_search_suggestion_success",
]
